export enum EvaluatorTypes {
  EVALUATE_TEXT_SUCCESS = "EVALUATE_TEXT_SUCCESS",
  EVALUATE_TEXT_PENDING = "EVALUATE_TEXT_PENDING",
  EVALUATE_TEXT_ERROR = "EVALUATE_TEXT_ERROR",

  GET_SESSION_ID_SUCCESS = "GET_SESSION_ID_SUCCESS",
  GET_SESSION_ID_PENDING = "GET_SESSION_ID_PENDING",
  GET_SESSION_ID_ERROR = "GET_SESSION_ID_ERROR",

  GET_ALL_RELATIONS_SUCCESS = "GET_ALL_RELATIONS_SUCCESS",
  GET_ALL_RELATIONS_PENDING = "GET_ALL_RELATIONS_PENDING",
  GET_ALL_RELATIONS_ERROR = "GET_ALL_RELATIONS_ERROR",

  UPLOAD_RELATIONS_SUCCESS = "UPLOAD_RELATIONS_SUCCESS",
  UPLOAD_RELATIONS_PENDING = "UPLOAD_RELATIONS_PENDING",
  UPLOAD_RELATIONS_ERROR = "UPLOAD_RELATIONS_ERROR",
}
